# Generated by Django 3.2.9 on 2021-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_desc_contact_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=50)),
                ('lecturer_email', models.CharField(max_length=50)),
                ('lecturer_subject', models.CharField(max_length=50)),
            ],
        ),
    ]
